const DATABASE_MODELS = {
    EXERCISE: "Exercise",
    MUSCLE: "Muscle",
    SPLIT: "Split",
    WORKOUT: "Workout",
    WORKOUT_SESSION: "WorkoutSession",
    USER: "User",
    CALORIES_COUNTER_ITEM: "CaloriesCounterItems",
    CALORIES_COUNTER_DAY: "CaloriesCounterDay",
    CALORIES_COUNTER_DAILY_GOAL: "CaloriesCounterDailyGoal",
    DAILY_WEIGHT: "DailyWeight",
    SUGGESTION: "Suggestion",
    SUPPLEMENTS: "Supplements",
    PERSONAL_TRAINER: "PersonalTrainer",
    RELATION: "Relation",
    DIET_PLAN: "DietPlan",
    REVIEW: "Review",
    CHAT: "Chat",
    MESSAGE: "Message",
    CONTENT: "Content"
}

const COLLECTIONS = {
    EXERCISES: "exercises",
    MUSCLES: "muscles",
    SPLITS: "splits",
    WORKOUTS: "workouts",
    WORKOUT_SESSIONS: "workoutSessions",
    USERS: "users",
    CALORIES_COUNTER_ITEMS: "caloriesCounterItems",
    CALORIES_COUNTER_DAYS: "caloriesCounterDays",
    CALORIES_COUNTER_DAILY_GOALS: "caloriesCounterDailyGoals",
    DAILY_WEIGHTS: "dailyWeights",
    SUGGESTIONS: "suggestions",
    PERSONAL_TRAINERS: "personalTrainers",
    RELATIONS: "relations",
    DIET_PLANS: "dietPlans",
    REVIEWS: "reviews",
    CHATS: "chats",
    MESSAGES: "messages",
    CONTENTS: "contents",
}

const PERSONAL_TRAINER_STATUSES = {
    ACTIVE: "ACTIVE",
    BLOCKED: "BLOCKED",
    PENDING: "PENDING",
}

const CHAT_STATUSES = {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
    BLOCKED: "BLOCKED",
}

const RELATION_STATUSES = {
    ACTIVE: "ACTIVE",
    DECLINED: "DECLINED",
    PENDING_APPROVAL: "PENDING_APPROVAL",
    CANCELED: "CANCELED"
}

const PROFESSIONS = {
    NUTRITIONIST: "NUTRITIONIST",
    DIETITIAN: "DIETITIAN",
    PERSONAL_TRAINER: "PERSONAL_TRAINER",
    NOT_GIVEN: "NOT_GIVEN"
}

const CARD_COLLECTIONS = [
    COLLECTIONS.DAILY_WEIGHTS,
    COLLECTIONS.WORKOUT_SESSIONS,
    COLLECTIONS.CALORIES_COUNTER_DAYS
]

const DB_URI = "mongodb://127.0.0.1:27017/FOUNDATIONAL";

const JWT_SECRET = "lj1ds21idpk2]312d's[23123q";

const PORT = 4057;

const NODE_ENVIRONMENTS = {
    DEVELOPMENT: "DEVELOPMENT",
    PRODUCTION: "PRODUCTION",
}

const NODE_ENVIRONMENT = NODE_ENVIRONMENTS.PRODUCTION;

const HTTP_STATUS_CODES = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    INTERNAL_SERVER_ERROR: 500,
}

const ROOT_URL_API = `https://api.gymrats.uploy.app`;

const UNITS = {
    1: ["sets", "reps", "kgs"],
    2: ["sets", "duration"],
    3: ["sets", "reps"],
}

const CALORIES_COUNTER_UNITS = {
    MILLILITERS: "MILLILITERS",
    GRAMS: "GRAMS"
}

const WEIGHT_UNITS = {
    POUNDS: "POUNDS",
    KILOGRAMS: "KILOGRAMS",
}

const CALORIES_COUNTER_MEALS = {
    BREAKFAST: "BREAKFAST",
    LUNCH: "LUNCH",
    DINNER: "DINNER",
    SNACKS: "SNACKS",
}

const SENDGRID_API_KEY = "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";

const APP_EMAIL = "support@uploy.app";

const WEIGHT_UNIT_RELATIONS = {
    KILOGRAMS: {
        POUNDS: 2.20462,
    },
    POUNDS: {
        KILOGRAMS: 0.453592
    }
}

const GOOGLE_API_KEY = "AIzaSyAYQnnCgQuzHGk6WMcbhtOPJHROn5vycE4";

const CONTENT_VISIBILITY_SCOPES = {
    PUBLIC: "PUBLIC",
    CLIENTS: "CLIENTS",
}

const DEFAULT_ERROR_MESSAGE = "Internal server error";

const SUGGESTIONS_STATUSES = {
    PENDING_REVIEW: "PENDING_REVIEW",
    ANSWERED: "ANSWERED"
}

module.exports = {
    DATABASE_MODELS: DATABASE_MODELS,
    DB_URI: DB_URI,
    COLLECTIONS: COLLECTIONS,
    PORT: PORT,
    NODE_ENVIRONMENT: NODE_ENVIRONMENT,
    NODE_ENVIRONMENTS: NODE_ENVIRONMENTS,
    HTTP_STATUS_CODES: HTTP_STATUS_CODES,
    JWT_SECRET: JWT_SECRET,
    ROOT_URL_API: ROOT_URL_API,
    UNITS: UNITS,
    CALORIES_COUNTER_UNITS: CALORIES_COUNTER_UNITS,
    WEIGHT_UNITS: WEIGHT_UNITS,
    SENDGRID_API_KEY: SENDGRID_API_KEY,
    CALORIES_COUNTER_MEALS: CALORIES_COUNTER_MEALS,
    CARD_COLLECTIONS: CARD_COLLECTIONS,
    APP_EMAIL: APP_EMAIL,
    PERSONAL_TRAINER_STATUSES: PERSONAL_TRAINER_STATUSES,
    RELATION_STATUSES: RELATION_STATUSES,
    PROFESSIONS: PROFESSIONS,
    WEIGHT_UNIT_RELATIONS: WEIGHT_UNIT_RELATIONS,
    GOOGLE_API_KEY: GOOGLE_API_KEY,
    CHAT_STATUSES: CHAT_STATUSES,
    CONTENT_VISIBILITY_SCOPES: CONTENT_VISIBILITY_SCOPES,
    DEFAULT_ERROR_MESSAGE: DEFAULT_ERROR_MESSAGE,
    SUGGESTIONS_STATUSES: SUGGESTIONS_STATUSES
}